#### Basics of Numpy

In [1]:
# Importing Numpy
import numpy as np
import sys

In [2]:
# Creating a 1D Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Creating a 2D Array
b = np.array([[4,5,6],[7,8,9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [4]:
# Getting the dimension
a.ndim


1

In [5]:
# Getting the shape
b.shape

(2, 3)

In [6]:
# Data Type
a.dtype

dtype('int64')

In [7]:
# Get size
b.itemsize

8

#### Accessing the element

In [8]:
# Get a specific element [Row, Column]
print(b[1,2]) 
print(b[0,-1]) # With negative index

9
6


In [9]:
# Get a specific row
b[0,:]

array([4, 5, 6])

In [10]:
# Get a specific column
b[:, 1]

array([5, 8])

In [11]:
# Getting specific element by index
b[0, 0:2:1]

array([4, 5])

In [12]:
# Changing an element
a[1]=5
a

array([1, 5, 3])

#### 3D Array

In [13]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
# Fetching a specific element
c[1,1,0]

np.int64(7)

#### Initializing different types of Arrays

In [15]:
# All 0s in matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
# All 1s in martrix
np.ones((4,2,2), dtype=int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [17]:
# Any number full method
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

In [18]:
# Any number full_like method
np.full_like(c, 5)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [19]:
# Random decimal numbers
np.random.rand(4,5)

array([[0.94427674, 0.80869803, 0.89877261, 0.2411185 , 0.91525769],
       [0.65724235, 0.22174835, 0.0631215 , 0.83302291, 0.49966969],
       [0.0348682 , 0.76635998, 0.39527055, 0.00799613, 0.16109222],
       [0.76735957, 0.19333364, 0.17100552, 0.45644743, 0.28576881]])

In [20]:
# Random integer values
np.random.randint(2,7, size=(3,3))

array([[3, 2, 2],
       [4, 5, 5],
       [2, 4, 5]], dtype=int32)

In [21]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# Repeating an array
arr = np.array([[1,7,9]])
arr_repeat = np.repeat(arr,3, axis=0)
arr_repeat

array([[1, 7, 9],
       [1, 7, 9],
       [1, 7, 9]])

#### Mathematics

In [23]:
d = np.array([1,2,3,4])
d

array([1, 2, 3, 4])

In [24]:
d*2

array([2, 4, 6, 8])

In [25]:
d + 2

array([3, 4, 5, 6])

In [26]:
d ** 3

array([ 1,  8, 27, 64])

#### Statistics

In [27]:
stats =np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(np.min(stats))

1


In [29]:
print(np.max(stats))

6


In [30]:
np.min(stats, axis=0)

array([1, 2, 3])

In [31]:
np.sum(stats)

np.int64(21)

#### Reorganizing arrays

In [32]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
after = before.reshape(4,2)
print(before)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
# Vertically stack arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
# Horizontally stack arrays
h1 = np.ones([2,4])
h2 = np.zeros([2,2])

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])